# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_song_name_artist_alter_album_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.song', verbose_name='Название песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='rest_app.artist', verbose_name='Имя артиста'),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son', to='rest_app.album', verbose_name='Из альбома'),
        ),
    ]
