# Generated by Django 4.2.6 on 2023-10-29 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_app', '0005_album_name_song_alter_song_name_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num', to='rest_app.song', verbose_name='Название песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.artist', verbose_name='Имя артиста'),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='rest_app.album', verbose_name='Из альбома'),
        ),
    ]
